from enum import Enum


class ErrorCode(str, Enum):
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    FORBIDDEN = "FORBIDDEN"
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    PATIENT_NOT_REGISTERED = "PATIENT_NOT_REGISTERED"
    CARE_CONTEXT_NOT_REGISTERED = "CARE_CONTEXT_NOT_REGISTERED"
    INVALID_REQUEST = "INVALID_REQUEST"
    CALLBACK_NOT_CORRELATED = "CALLBACK_NOT_CORRELATED"
    WEBHOOK_CONFIG_MISSING = "WEBHOOK_CONFIG_MISSING"
    WEBHOOK_NON_RETRYABLE = "WEBHOOK_NON_RETRYABLE"
    DATA_PUSH_URL_INVALID = "DATA_PUSH_URL_INVALID"
    DATA_DECRYPTION_FAILED = "DATA_DECRYPTION_FAILED"
    UPSTREAM_ERROR = "UPSTREAM_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
